In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [7]:
X = x.reshape((3, 4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X.shape

torch.Size([3, 4])

In [9]:
X.numel()

12

In [12]:
X = X.reshape((4, -1))
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [13]:
x = torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
x = torch.ones((2,3,4))
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
x = torch.randn((3,4))
x

tensor([[ 1.1050, -0.3123, -0.7163, -1.9675],
        [-0.9449, -0.0199, -0.4292,  0.3471],
        [-0.8333,  1.7585, -0.5965, -0.7844]])

In [17]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x = torch.tensor([1, 2, 3, 8])
y = torch.tensor([2,2,2,2])

x+y, x-y, x*y, x/y, x**y

(tensor([ 3,  4,  5, 10]),
 tensor([-1,  0,  1,  6]),
 tensor([ 2,  4,  6, 16]),
 tensor([0.5000, 1.0000, 1.5000, 4.0000]),
 tensor([ 1,  4,  9, 64]))

In [23]:
z = torch.exp(x)
z

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 2.9810e+03])

In [24]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [27]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [64]:
torch.cat((X, Y), dim=1)

tensor([[ 3.,  3.,  2.,  2.,  5.,  4.,  6.,  5.],
        [ 3.,  3.,  2.,  2.,  4.,  5.,  5.,  6.],
        [ 8.,  9., 10., 11., 12., 12., 12., 12.]])

In [29]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [30]:
X.sum()

tensor(66.)

In [31]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [33]:
a*b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [34]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [40]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [44]:
X[:2, :2] = 3
X

tensor([[ 3.,  3.,  2.,  2.],
        [ 3.,  3.,  2.,  2.],
        [ 8.,  9., 10., 11.]])

In [51]:
X, Y

(tensor([[ 3.,  3.,  2.,  2.],
         [ 3.,  3.,  2.,  2.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [52]:
before = id(Y)
Y = X + Y
after = id(Y)

In [53]:
before

2039013428344

In [54]:
after

2039013512120

In [55]:
Z = torch.zeros_like(Y)

print(id(Z))

Z[:] = X+Y

print(id(Z))

2038892410904
2038892410904


In [56]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [62]:
a = torch.tensor([1])
a, a.item(), int(a), float(a)

(tensor([1]), 1, 1, 1.0)