In [1]:
import torch

# 标量

In [2]:
# 变量由只有一个元素的张量表示

# 我们实例化两个标量
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

# 向量

In [3]:
# 向量可以视作由标量组成的列表
# 我们通过一维张量处理向量

# 注意：默认列向量是向量的方向！！

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
# 可以通过下标来引用向量的任意元素
x[2]

tensor(2)

In [5]:
# 向量的长度通常称谓向量的维度，可以通过Python内置的len()函数来获取
# 需要注意的是，“维度”这个词因为上下文可能会有歧义，对于向量来说，我们约定“维度”就是向量的长度
len(x)

4

# 矩阵

In [6]:
A = torch.arange(20).reshape((4, 5))
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [7]:
# 矩阵的转置
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

# 张量

In [8]:
# 张量为我们提供了描述具有任意数量轴的n维数组的通用方法

# 向量是一阶张量
# 矩阵是二阶张量

In [9]:
X = torch.arange(24).reshape((2,3,4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
# 给定具有相同形状的任意两个张量，任何按元素⼆元运算的结果都将是相同形状的张量

A = torch.arange(20, dtype=torch.float32).reshape((5,4))

B = A.clone() # 通过分配新内存，将A的一个副本分配给B

A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [11]:
# 两个矩阵的按元素乘法 称为 Hadamard积，数学符号就是一个圆圈带圆心
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [12]:
# 将张量乘以或加上⼀个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape(2,3,4)

a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [13]:
# 计算一个张量中所有元素的总和
X.sum()

tensor(276)

In [14]:
# 我们可以指定张量沿哪一个轴来通过求和降低维度
A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)

A, A_sum_axis0, A_sum_axis1

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 tensor([ 6., 22., 38., 54., 70.]))

In [16]:
# 沿着行和列对矩阵求和，等价于对矩阵所有元素求和
# 下面两行代码的作用一样

A.sum(), A.sum(axis=[0, 1])

(tensor(190.), tensor(190.))

In [17]:
# 跟求和类似，我们也可以求所有元素的平均值
# 下面代码的作用一样

A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [18]:
# 同样的，求平均值也可以指定按哪个轴
# 下面代码的作用一样

A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [20]:
# 也可以使求和后的“轴数”不变
sum_A = A.sum(axis=1, keepdims=True)

sum_A, A.shape, sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 4]),
 torch.Size([5, 1]))

In [21]:
# 计算沿某个轴的累计总和，调用cumsum()函数
# 此函数不会降维

A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [25]:
# 点积
# 注意！调用点积计算 torch.dot()函数，对于传入的张量参数的数据类型必须一致！！！否则报错！！！
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [27]:
# 点积同样可以由下述代码来计算
(x * y).sum(), torch.sum(x * y)

(tensor(6.), tensor(6.))

In [28]:
# 利用方阵的乘法来表示旋转

In [32]:
# torch.mv()函数用来计算矩阵—向量的乘积

A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [36]:
# torch.mm()函数用来计算矩阵——矩阵的乘积
B = torch.ones(A.T.shape)

torch.mm(A, B), A.shape, B.shape, torch.mm(A, B).shape

(tensor([[ 6.,  6.,  6.,  6.,  6.],
         [22., 22., 22., 22., 22.],
         [38., 38., 38., 38., 38.],
         [54., 54., 54., 54., 54.],
         [70., 70., 70., 70., 70.]]),
 torch.Size([5, 4]),
 torch.Size([4, 5]),
 torch.Size([5, 5]))

In [37]:
# 注意：矩阵的乘法不要和Hadamard积搞混了！
A_ = A.clone()
A * A, A

(tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

# 范数

In [38]:
# 在线性代数中，向量范数是将向量映射到标量的函数F

# 向量的范数要满足3个性质：
# 1. 缩放性
# 2. 三角不等式
# 3. 非负

In [39]:
# torch.norm()函数用来计算范数，默认是L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [40]:
# L1范数的计算
torch.abs(u).sum()

tensor(7.)

In [41]:
# torch.norm()函数可以直接计算一个矩阵的范数
torch.norm(A)

tensor(49.6991)

In [45]:
# 注意：高阶张量在调用内置的len()函数时，返回的是其第一个维度
X.shape, len(X)

(torch.Size([2, 3, 4]), 2)

In [49]:
X, X.sum(axis=0), X.sum(axis=1), X.sum(axis=2)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))